#!/usr/bin/env bash
# good luck and bad luck, best school

x=1
while ((x<=10))
do
	
	if ((x==4)); then
	echo "bad luck"
	elif ((x==8)); then
	echo "good luck"
	else
	echo "Best School"
	fi
	((x++))
done
