#!/usr/bin/env bash
# Using the case statement to print multi qualifiers
x=1
while ((x<=20))
do
case "$x" in
	4)
		echo "$x"
		echo "bad luck fom china"
		;;
	9)
		echo "$x"
		echo "bad luck from japan"
		;;
	17)
		echo "$x"
		echo "bad luch from Italy"
		;;
	*)
		echo "$x"
		;;
esac
((x++))
done
